# Vi-style selection
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel

# Increase scrollback buffer size
set -g history-limit 50000

# Start window and pane numbering from 1 for easier switching
set -g base-index 1
setw -g pane-base-index 1

# Allow tmux to set the terminal title
set -g set-titles on

# Allow automatic renaming of windows
set -g allow-rename on

# Renumber windows when one is removed.
set -g renumber-windows on

# Preseve extended keys
set -g xterm-keys on
set -g default-terminal "tmux-256color"

# Improve colors
set -as terminal-features ",*:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"

# Support undercurls
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Status bar
set-option -g status-position 'top'
set-option -g status 2
set-option -g status-format[1] ''
set-option -g status-style 'fg=#f8f9e8 bg=#22272e'
set-option -g status-left ''
set-option -g status-right ''
set-option -g status-justify left
set-option -g window-status-format '#[fg=#9aa1a7] #W '
set-option -g window-status-current-format '#[bg=#d0b46f,fg=#191e21 bold] #W '
set -g pane-active-border-style "fg=#606a76"
set -g pane-border-style 'fg=#606a76'
set-option -g window-status-separator ""
set-option -g message-style "bg=#191e21,fg=#f8f9e8"

# Don't show distracting notifications
set -g visual-bell off
set -g visual-activity off

# Focus events enabled for terminals that support them
set -g focus-events on

# Remove vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Change prefix to "Ctrl+x"
set -g prefix C-x
bind C-x send-prefix

# Reload of the config file with "Ctrl+x r"
unbind r
bind r source-file ~/.tmux.conf\; display-message '~/.tmux.conf reloaded'

# Panes
## Resize panes
bind -n M-z resize-pane -Z
bind -n M-h resize-pane -L 2
bind -n M-j resize-pane -D 1
bind -n M-k resize-pane -U 1
bind -n M-l resize-pane -R 2

## Split panes (staying in same directory)
bind -n M-/ split-window -h -c "#{pane_current_path}"
bind -n M-- split-window -v -c "#{pane_current_path}"

# Select or create window
bind -n M-1 run-shell 'tmux select-window -t 1 2>/dev/null || tmux new-window -t 1'
bind -n M-2 run-shell 'tmux select-window -t 2 2>/dev/null || tmux new-window -t 2'
bind -n M-3 run-shell 'tmux select-window -t 3 2>/dev/null || tmux new-window -t 3'
bind -n M-4 run-shell 'tmux select-window -t 4 2>/dev/null || tmux new-window -t 4'
bind -n M-5 run-shell 'tmux select-window -t 5 2>/dev/null || tmux new-window -t 5'
bind -n M-6 run-shell 'tmux select-window -t 6 2>/dev/null || tmux new-window -t 6'
bind -n M-7 run-shell 'tmux select-window -t 7 2>/dev/null || tmux new-window -t 7'
bind -n M-8 run-shell 'tmux select-window -t 8 2>/dev/null || tmux new-window -t 8'
bind -n M-9 run-shell 'tmux select-window -t 9 2>/dev/null || tmux new-window -t 9'
bind -n M-0 run-shell 'tmux select-window -t 10 2>/dev/null || tmux new-window -t 10'

# Plugins

## TMUX/VIM navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

## Extractor popup
set -g @plugin 'laktak/extrakto'
bind -n M-n run-shell "~/.tmux/plugins/extrakto/scripts/open.sh \"#{pane_id}\""

## TPM
set -g @plugin 'tmux-plugins/tpm'
setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"

if "test ! -d ~/.tmux/plugins/tpm" \
       "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run -b '~/.tmux/plugins/tpm/tpm'
